config/routes.rb
Michielsvleeswaren::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/signup', :to => 'users#new'
  
  match '/signin', :to => 'sessions#new'
  
  match '/signout', :to => 'sessions#destroy'  

  root :to => 'pages#home'
  
  match '/home', :to => 'pages#home'
  
  match '/verkoop', :to => 'pages#verkoop'
  
  match '/productie', :to => 'pages#productie'
  
  match '/administratie', :to => 'pages#administratie'
  
  match '/signup', :to => 'users#new'
  
  get "pages/home"

  get "pages/verkoop"

  get "pages/productie"
  
  get "pages/administratie"

end

app/models/user.rb
# == Schema Information
# Schema version: 20110622164315
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,  :presence => true,
                    :length => { :maximum => 50 }
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence      => true,
                       :confirmation  => true,
                       :length        => { :within => 6..40}
  before_save :encrypt_password
  
  # Return true if the user's password matches the submitted password
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  private
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def verkoop
    @title = "Verkoop"
  end

  def productie
    @title = "Productie"
  end
  
  def administratie
    @title = "Administratie"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end
  
  def create
    user = User.authenticate(params[:session][:email], params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_back_or user
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => :destroy
  
  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def new
    @user = User.new
    @title = "Gebruikers"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welkom bij Michiels Vleeswaren"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  def edit
    @title = "Edit user"
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  private
  
    def authenticate
      deny_access unless signed_in?
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def logo
    logo = image_tag("logo.png", :alt => "Michiels Vleeswaren | 100% uw smaak", :class => "logo", :width => "381", :height => "83")
  end

  
  #Return a title on a per-page basis
  def title
    base_title = "Michiels Vleeswaren"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  
  private
  
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end
    
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
    
    def store_location
      session[:return_to] = request.fullpath
    end
    
    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="content">
        <div class="menu2">
        <ul id="key">
            <li class="key"><%= link_to_unless_current("Gebruikers", signup_path, :class => "menuitem") do
				link_to("Gebruikers", signup_path, :class => "menuitem selected")
			end
			%></li>
        </ul>
        <ul class="items">
            <li><%= link_to "Michiels Vleeswaren", "http://www.michiels-vleeswaren.be", :class => "menuitem", :title => "Michiels Vleeswaren online"%></li>
            <li><%= link_to "Jac. Michiels", "http://www.jacmichiels.be", :class => "menuitem", :title => "Jac. Michiels online"%></li>
			<li><%= link_to "Fenavian", "http://www.fenavian.be", :class => "menuitem", :title => "De vereniging voor vlees en vleeswaren bedrijven"%></li>
			<li><%= link_to "FAVV", "http://www.favv.be", :class => "menuitem", :title => "FOD Voedselveiligheid"%></li>
			<li><%= link_to "Flanders' Food", "http://www.flandersfood.be", :class => "menuitem", :title => "De competentiepool van de Vlaamse Voedingsindustrie"%></li>
        </ul>
        </div><!--einde menu2-->
    </div><!--einde content-->
</div><!--einde footer-->

app/views/layouts/_header.html.erb
<div id="header">
<div class="content">
	<%= link_to logo, root_path %>
	
	<div class="menu">
		<ul id="home">
			<li class="home"><%= link_to_unless_current("Home", root_path, :class => "menuitem") do
				link_to("Home", root_path, :class => "menuitem selected")
			end
			%></li>
		</ul>
		<ul class="items">
			
			<% if signed_in? %>
			<li><%= link_to_unless_current("Profiel", current_user, :class => "menuitem") do
				link_to("Profiel", current_user, :class => "menuitem selected")
			end
			%></li>	
			<li><%= link_to_unless_current("Users", users_path, :class => "menuitem") do
				link_to("Users", users_path, :class => "menuitem selected")
			end
			%></li>
			<li><%= link_to_unless_current("Settings", edit_user_path(current_user), :class => "menuitem") do
				link_to("Settings", edit_user_path(current_user), :class => "menuitem selected")
			end
			%></li>					
			<% end %>
						
			<li><%= link_to_unless_current("Verkoop", verkoop_path, :class => "menuitem") do
				link_to("Verkoop", verkoop_path, :class => "menuitem selected")
			end
			%></li>
			<li><%= link_to_unless_current("Productie", productie_path, :class => "menuitem") do
				link_to("Productie", productie_path, :class => "menuitem selected")
			end
			%></li>
			<li><%= link_to_unless_current("Administratie", administratie_path, :class => "menuitem") do
				link_to("Administratie", administratie_path, :class => "menuitem selected")
			end
			%></li>
			<% if signed_in? %>
			<li><%= link_to_unless_current("Sign out", signout_path, :class => "menuitem") do
				link_to("Sign out", signout_path, :class => "menuitem selected")
			end
			%></li>
			<% else %>
			<li><%= link_to_unless_current("Sign in", signin_path, :class => "menuitem") do
				link_to("Sign in", signin_path, :class => "menuitem selected")
			end
			%></li>
			<% end %>
	</div><!--einde menu-->
</div><!--einde content-->
</div><!--einde header-->

app/views/layouts/_headertop.html.erb
<div id="headertop">
	<div class="content">
		<ul class="lang">
		<li><a class="langa" href="#">nl</a></li>
		<li><a class="langa" href="#">fr</a></li>
		<li><a class="langa" href="#">en</a></li>
		</ul>
	</div><!--einde content-->
</div><!--einde headertop-->

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'michiels', :media => 'screen' %>
<%= stylesheet_link_tag 'print', :media => 'print' %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
	<%= csrf_meta_tag %>	
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  	<%= javascript_include_tag 'prototype', 'scriptaculous', 'application', 'jquery', 'http://fast.fonts.com/jsapi/ba25e6c1-2e2e-47bc-bcde-f97c37d623a6.js' %>
	<script> var $j = jQuery.noConflict();
	</script>
	
		<title><%= title %></title>
		<%= render 'layouts/stylesheets' %>
	</head>
	<body>
		<div id="wrap">
		<div id="main">
			
		<%= render 'layouts/headertop' %>
		<%= render 'layouts/header' %>

		<div id="contentmiddle">
			<div class="content">
			</div>
		</div><!-- einde contentmiddle -->
				
		<div id="contentbottom">
			<div class="content">
			<section class="round">
				<% flash.each do |key, value| %>
					<div class="flash <%= key %>"><%= value %></div>
				<% end %>
				<%= yield %>
			</section>
			<%= debug(params) if Rails.env.development? %>
		    </div><!--einde content-->
		</div><!--einde content v contentbottom-->
		
		<p class="clear"></p>
	
		</div><!-- einde main -->
					
		<%= render 'layouts/footer' %>
		
				
		</div><!-- einde wrap -->
		
		<div id="mti_wfs_colophon">
		</div>

		<script type="text/javascript">
		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-9957234-39']);
		  _gaq.push(['_trackPageview']);

		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
		</script>

	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
		from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, :size => 150 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? %>
	| <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
								  :title => "Delete #{user.name}" %>
	<% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<% @users.each do |user| %>
		<%= render @users %>
	<% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
	<tr>
		<td class="main">
			<h1>
				<%= gravatar_image_tag @user.email, :class => "gravatar" %>
				<%= @user.name %>
			</h1>
		</td>
		<td class="sidebar round">
			<strong>Name</strong> <%= @user.name %><br />
			<strong>URL</strong> <%= link_to user_path(@user), @user %>
		</td>
	</tr>
</table>